### PR TITLE
Fix type hierarchy comparisons of types no longer visible in API

### LINKED ISSUE #251: extension method widening a parameter should not be a breaking change
**Describe the bug**

```json
{
  "breakingChanges": {
    "label": "BREAKING CHANGES",
    "children": [
      {
        "label": "Class BuildOutputBuilderAddDataAssetsDirectories",
        "children": [
          {
            "label": "Method addDataAssetDirectories",
            "children": [
              {
                "changeDescription": "Type of parameter \"input\" changed. BuildInput -> HookInput",
                "changeCode": "CE08",
                "isBreaking": true,
                "type": "major"
              }
            ]
          }
        ]
      }
    ]
  }
}
```

```dart
final class BuildInput extends HookInput {
```

```dart
extension BuildOutputBuilderAddDataAssetsDirectories on BuildOutputBuilder {
```

Extensions cannot be implemented, so widening a parameter type should be a non-breaking change.

**Actual and Expected behavior**
Not breaking change.

**System info (please complete the following information):**
 - dart_apitool version: 8654b768219d5707cdade72fdd80cf915e9d46b8

**Additional context**
https://github.com/dart-lang/native/actions/runs/18614286356/job/53076701689?pr=2712

### PR DESCRIPTION
**Pull request by devmil**
## Description
When types are no longer part of the public API but are needed to derive the type relation (like to find our if the new type is wider / narrower as the old one) then the type hierarchy used to calculate that information did no longer know about the type and its relations.

This PR merges the TypeHierarchy by taking all types not known in the new TypeHierarchy from the old one.

## Type of Change

- [ ] 🚀 New feature (non-breaking change)
- [x] 🛠️ Bug fix (non-breaking change)
- [ ] ⚠️ Breaking change (feature or bug fix which breaks existing behaviors/APIs)
- [ ] 🏗️ Code refactor
- [ ] ⚙️ Build configuration change
- [ ] 📝 Documentation
- [ ] 🧹 Chore / Housekeeping

Fixes #251

### CODE REVIEW

File: lib/src/model/type_hierarchy.dart [hunk 1]
```diff
@@ -232,6 +232,55 @@ class TypeHierarchy {
...
+      // and remove all occurences that don't match
+      final matchingItems = items.where((i) =>
+          i.typeIdentifier.packageRelativeLibraryPath ==
+          typeIdentifier.packageRelativeLibraryPath);
+      if (matchingItems.isEmpty) {
+        return {};
+      }
+      if (matchingItems.length > 1) {
+        // we still have multiple matching items => we can't tell which one to use
+        return {};
```
Comment (adamgic) [inline lib/src/model/type_hierarchy.dart]: The name of this function and documentation do not suggest that there is such a matching done here. Function has the same result for type not found, type not found in path, multiple types defined with same name and at the same path - these are all edge cases (some are wrong resulting with analyser/compiler errors), but the function treat all the same. I wonder if it should return null or throw.
