### PR TITLE
fix: relative package path handling

### LINKED ISSUE #237: Unable to use --extract in a workspace?
Does `--extract` support workspaces? I can't figure out how to use it in a workspace.

I'm trying it with https://github.com/google/protobuf.dart. I want to extract the API for `protobuf`. Using the `master` branch I get this: (in the repo root)

```
$ dart-apitool extract --input protobuf
Preparing protobuf
Copying sources from protobuf
Could not find workspace for package protobuf
Could not find workspace for package /tmp/JITPPV
Error: PathNotFoundException: Cannot open file, path = 'protobuf/.dart_tool/package_config.json' (OS Error: No such file or directory, errno = 2)
```

If I use `.` as the input I get this:

```
$ dart-apitool extract --input .
 Preparing .
Copying sources from .
Omitting pub get (package config already present)
Analyzing .
Cleaning up
{
    "version": 3,
    "packageApi": {
        "packageName": "workspace",
        "packageVersion": null,
        "packagePath": "/tmp/NSKLVJ",
        "interfaceDeclarations": [],
        "executableDeclarations": [],
        "fieldDeclarations": [],
        "typeAliasDeclarations": [],
        "semantics": [
            "containsPlatformConstraints"
        ],
        "iosPlatformConstraints": null,
        "androidPlatformConstraints": null,
        "sdkType": "dart",
        "minSdkVersion": "3.7.0",
        "packageDependencies": []
    },
    "missingEntryPoints": []
}
```

Which doesn't show the API so I'm guessing it's not doing anything?

What's the expected output of this command when it works? It might be useful to show it in the README.

I also can't figure out how to extract APIs using `git://...` as `--input`. As an example, what's the full command for generating the API of https://github.com/dart-lang/core/tree/main/pkgs/collection ? I think the syntax shown in the README with `git://https://...` is probably wrong as they generate "Unknown package ref".

### PR DESCRIPTION
**Pull request by devmil**
## Description
This PR fixes an issue with relative package paths

fixes #237 

## Type of Change

- [ ] 🚀 New feature (non-breaking change)
- [x] 🛠️ Bug fix (non-breaking change)
- [ ] ⚠️ Breaking change (feature or bug fix which breaks existing behaviors/APIs)
- [ ] 🏗️ Code refactor
- [ ] ⚙️ Build configuration change
- [ ] 📝 Documentation
- [ ] 🧹 Chore / Housekeeping

### CODE REVIEW

File: lib/src/tooling/dart_interaction.dart [hunk 1]
```diff
@@ -133,6 +133,12 @@ abstract class DartInteraction {
       String newPackageName
     })? packageNameReplacementInfo,
   }) async {
+    if (path.isRelative(fromPackage)) {
```
Comment (ThiagoEvoaCtw) [inline lib/src/tooling/dart_interaction.dart:136]: Does it make sense to extract it to a method, so giving a name to it would help understand the necessity of this change.

Comment (devmil) [reply lib/src/tooling/dart_interaction.dart:142]: good point. I added a comment and an API doc for getPackageConfigPathForPackage
